### ISSUE TITLE
SQLite: Generated SQL attempts to insert into identity column on InsertOrUpdate action

### ISSUE THREAD

**Issue by triforcely** [videokojot/EFCore.BulkExtensions.MIT#131]
SQLite adapter attampts to insert identity column when doing bulk inserts. This results in "0" being inserted as id when data set has no conflicts but results in unique constraint violation if our data set is not unique.

**Comment by triforcely** [comment]
Hey @videokojot , any chance you could take a look at this?

**Comment by triforcely** [comment]
@videokojot  I hate to be pushy about this, but is there any chance we could fast-track this? 🙏

**Comment by videokojot** [comment]
Hi, sorry I am busy right now, but I will try to look at it this evening or
over the weekend.

**Comment by triforcely** [comment]
For reference, proposed fix is here: https://github.com/videokojot/EFCore.BulkExtensions.MIT/pull/138

**Comment by videokojot** [comment]
Fixed in #138 . Thank you. 

New version released: https://github.com/videokojot/EFCore.BulkExtensions.MIT/releases/tag/17.0
