### ISSUE TITLE
Upgrade to release version of NET8

### ISSUE THREAD

**Issue by videokojot** [videokojot/EFCore.BulkExtensions.MIT#72]
We need to wait for following issues to be fixed:
- when the NET8 verison for Postgre is released:
https://github.com/npgsql/efcore.pg/issues/2941
- and when the NET8 version for MySQl is releasd:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1746
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1808

**Comment by videokojot** [comment]
@binaryevents thanks for heads up. 

I am still waiting for the MySql to be upgraded to release version (it is still on 8.0.0beta2) so I can release also the main package (which contains all of the SQL provider) together.
But they should release very soon, see:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1746#issuecomment-1839066128

But if it would help you I can release other (other than MySQL) packages with upgraded dependecies and on release versions.

**Comment by binaryevents** [comment]
Hi @videokojot,
I think we are fine waiting some more days. We are currently using pre-release and no production release is planed in near future.
But thanks for the offer. :-)

**Comment by binaryevents** [comment]
Just an heads up. Probably you already know: Version[ 8.0.0 of Pomelo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/8.0.0) was finally released 🥳

**Comment by videokojot** [comment]
Hi @binaryevents I have just released new version (https://github.com/videokojot/EFCore.BulkExtensions.MIT/releases/tag/15.0) for NET8 with the release version of Pomelo.
