### ISSUE TITLE
PropertiesToIncludeOnUpdate

### ISSUE THREAD

**Issue by PJH-Eric** [videokojot/EFCore.BulkExtensions.MIT#84]
// When need to Insert only new and skip existing ones in Db (Insert_if_not_Exist) then use BulkInsertOrUpdate with this list set to empty: <c>new List<string> { "" }</string></c>
                    PropertiesToIncludeOnUpdate = new List<string> { "" },

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by videokojot** [comment]
Thanks for the report, I will try to replicate and fix it.

**Comment by videokojot** [comment]
I finnaly got to it. It is fixed in:
https://github.com/videokojot/EFCore.BulkExtensions.MIT/pull/92

**Comment by videokojot** [comment]
Fix is included in version **(6/7/8).14.0**+  see:
https://github.com/videokojot/EFCore.BulkExtensions.MIT/releases/tag/14.0

It is already available on nuget.org:
https://www.nuget.org/packages/EFCore.BulkExtensions.MIT
